version: '3.6'

services:
  front-end:
    image: weaveworksdemos/front-end:0.3.12
    hostname: front-end
    cap_drop:
      - all
    read_only: false

  edge-router:
    image: weaveworksdemos/edge-router:0.1.1
    ports:
      - '80:80'
      - '8080:8080'
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: false
    hostname: edge-router

  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    hostname: catalogue
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true

  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    hostname: catalogue-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb

  carts:
    image: weaveworksdemos/carts:0.4.8
    hostname: carts
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: false
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false

  carts-db:
    image: mongo:3.4
    hostname: carts-db
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: false

  orders:
    image: weaveworksdemos/orders:0.4.7
    hostname: orders
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: false
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false

  orders-db:
    image: mongo:3.4
    hostname: orders-db
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: false

  shipping:
    image: weaveworksdemos/shipping:0.4.8
    hostname: shipping
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: false
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false

  queue-master:
    image: weaveworksdemos/queue-master:0.3.1
    hostname: queue-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: false

  rabbitmq:
    image: rabbitmq:3.6.8
    hostname: rabbitmq
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
    
  payment:
    image: weaveworksdemos/payment:0.4.3
    hostname: payment
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: false

  user:
    image: weaveworksdemos/user:0.4.4
    hostname: user
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: false
    environment:
      - MONGO_HOST=user-db:27017

  user-db:
    image: weaveworksdemos/user-db:0.4.0
    hostname: user-db
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: false
    volumes:
      - type: tmpfs
        target: /tmp:rw,noexec,nosuid

  user-sim:
    image: weaveworksdemos/load-test:0.1.1
    cap_drop:
      - all
    read_only: false
    hostname: user-simulator
    command: "-d 60 -r 200 -c 2 -h edge-router"